### ISSUE TITLE
The action doesn't output displays for matlab scripts

### ISSUE THREAD

**Issue by nishante** [matlab-actions/run-command#57] opened 2024-04-15 18:35 UTC
I have a matlab script that defines a function with a return value. When I run this function inside the matlab command window, it outputs all the `disp`s added inside the body of the function (for logging and debug) as well as the function's return value. I tried this with Matlab's batch mode as well (`matlab.exe -nodesktop -nosplash -batch myFunction`) and got the same results. However, when I run the same function using the `matlab-actions/run-command@v2` action, it _only_ outputs the function return value and none of the `disp`s are displayed in the output.

I've noticed that for another invocation of this action where I am calling a matlab script that builds a Simulink model using `rtwbuild` (in addition to doing other things), it _does_ output all the information that simulink outputs in the diagnostic window. So I also tried using `sldiagviewer.reportInfo` but still the output didn't show up.

Maybe this is something Matlab-specific, or maybe I am missing something obvious (or maybe this is intentional with a possible workaround?). If so, please let me know.

**Comment by nishante** [comment] 2024-04-15 19:04
Matlab version is "9.14.0.2337262 (R2023a) Update 5". Operating system is Windows 10. It is a self-hosted AWS server.

**Comment by mcafaro** [comment] 2024-04-15 19:22
I am not able to reproduce this issue by trying to run [myfunc.m](https://github.com/mcafaro/nodisp/blob/main/myfunc.m) with MATLAB R2023a on a Windows runner.

See my [workflow YAML](https://github.com/mcafaro/nodisp/blob/main/.github/workflows/ci.yml) and [job log](https://github.com/mcafaro/nodisp/actions/runs/8694774590/job/23844387531).

<img width="364" alt="Screenshot 2024-04-15 at 3 21 13 PM" src="https://github.com/matlab-actions/run-command/assets/34887852/f3c4e2e5-d83c-47f3-b053-5456b2466805">

Does it look like I am doing anything different than you?

**Comment by nishante** [comment] 2024-04-15 19:36
The only things I see different are:
- I am not running the setup-matlab action
- I am running this action on a pull request instead of a push

Neither of them seem like something that could be relevant here, however.

Here's my output on the CI:
![image](https://github.com/matlab-actions/run-command/assets/98344400/808817e5-8627-4f15-8d27-8f580e8b411d)

Here's my output in a Matlab command window:
![image](https://github.com/matlab-actions/run-command/assets/98344400/2ad62074-2ef8-4afc-8127-8219170acdb3)

Unfortunately, I cannot share the repository since it has locked access for my organization only.

**Comment by mcafaro** [comment] 2024-04-15 19:48
Is it possible there is a conditional around the `disp` statements that is evaluating to false on your runner? Can you try adding a simple `disp('hello world')` at the beginning of your function to simplify things as much as possible? If that doesn't work, can you put `which disp` at the top of your function to check that `disp` is not being shadowed?

It does appear like MATLAB is printing to the logs because `ans = ...` is being displayed.

**Comment by nishante** [comment] 2024-04-15 19:58
The `disp`s did not have any conditionals around them, but I still tried adding the two additional disps (one for hello world at the top of the function and the which disp) and got the same result.

CI:
![image](https://github.com/matlab-actions/run-command/assets/98344400/b26ec3c1-bde8-43aa-bee6-3f6839536b7e)

Local:
![image](https://github.com/matlab-actions/run-command/assets/98344400/2e8e9cb6-bdd4-4a69-ac77-976463e6b5b2)

**Comment by mcafaro** [comment] 2024-04-15 20:13
Can you try using the `-logfile` startup option to produce a log file and then print the contents of the log file, like so:

```yaml
- name: Run MATLAB command
  uses: matlab-actions/run-command@v2
  with:
    command: getGitVersionNumber
    startup-options: -logfile log.txt

- name: Display log.txt
  run: cat log.txt
```

Does the log.txt contain the output you would expect?

**Comment by nishante** [comment] 2024-04-15 21:13
Looks like the logfile _does_ contain the output locally (Windows 10, Matlab 2023a), but it _doesn't_ on the CI (Windows details below, Matlab 2023a). On the CI, the log file _only_ contains the `ans = ...` part.
![image](https://github.com/matlab-actions/run-command/assets/98344400/18eec576-abce-4d18-adb3-5a643539031c)

**Comment by nishante** [comment] 2024-04-15 23:40
Additional information which might help debug:

I noticed that in the output it calls an intermediate "C:\action-runner-org1\_work\_actions\matlab-actions\run-command\v2\dist\bin\win64\run-matlab-command.exe" and then passes two arguments:
- first argument as the matlab command to run two things:
  - change directory to a path in the temp folder and then set `MW_ORIG_WORKING_FOLDER` environment variable to it
  - run `command_<long string of digits>`, which I found existed on the CI computer temp folder as a matlab script that contains `cd(getenv('MW_ORIG_WORKING_FOLDER'));getGitVersionNumber`
- empty quotes `""`
 
Strangely, the path to "run-matlab-command.exe" above does not exist on the CI computer (it has the `matlab-actions/run-command/v1` folder, but not the `v2` folder there). Also, I am unsure where the `run-matlab-command.exe` comes from. Perhaps this executable behaves differently to the `matlab.exe` executable provided from the matlab installation?

I tried using the v1 binary and run the command above verbatim on the CI in a terminal window (`C:\action-runner-org6\_work\_actions\matlab-actions\run-command\v1\dist\bin\win64\run-matlab-command.exe "setenv('MW_ORIG_WORKING_FOLDER', cd('C:\Users\CONTRO~1\AppData\Local\Temp\run_matlab_command-8UDLI1'));command_89429a2e_8fdb_44d6_b924_c4899870b04e" ""`). However, it actually _did_ print all the output from the disp statements there, but neither do I see it on github when the action is run, nor do I see it in the generated logfile from above.

**Comment by mcafaro** [comment] 2024-04-16 13:22
Is it possible the workflow is running against the branch your pull request is *merging into* and not the branch being merged? And perhaps the branch being merged into does not have any `disp` statements in `getGitVersionNumber`?

Can you try to modify the `[99 99 99 7]` vector being printed by `ans` to ensure the code you expect to be running is actually running?

**Comment by nishante** [comment] 2024-04-16 22:03
I feel very stupid if that's the reason. I had expected for the merged commit to contain the new implementation of the function (with the disps) since it also clearly contains the new yml CI workflow file. It is also strange because the yml file contains the following:
```
- uses: actions/checkout@v4
        with:
            ref: ${{ github.event.pull_request.head.ref }}
            submodules: true
            token: ${{ steps.get_workflow_token.outputs.token }}
```

And according to the [documentation](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context), the `head_ref` should point to the _source branch of the pull request_. Furthermore, the output of this checkout workflow also shows that it is checking out the source branch (the one that contains the `disp`s) and also shows the exact commit hash of the commit being checked out (which lines up with the latest commit on the source branch).

In any case, I will try to trigger the workflow manually on the branch of interest (instead of a pull request trigger, which might run it on a merge commit) and I'll also try running it on a _merged_ branch that contains the new implementation with the `disp`s.

**Closed** 2024-04-16 22:14 UTC
